services:
  wp-cli:
    image: wordpress:cli
    user: "0"
    environment:
      WP_ENV: ${WP_ENV}
      WP_HOME: ${WP_HOME}
      WP_SITEURL: ${WP_SITEURL}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PREFIX: ${DB_PREFIX}
    command: bash -c "wp core install --url=$WP_HOME \
      --admin_user=$WP_USER \
      --admin_password=$WP_PASSWORD \
      --admin_email=$WP_EMAIL --allow-root
      && wp language core install ru_RU --allow-root
      && wp language core activate ru_RU --allow-root
      && wp plugin install https://awkirin.ru/wp/plugins/acf-extended-pro.zip --allow-root
      && wp plugin install https://awkirin.ru/wp/plugins/advanced-custom-fields-pro.zip --allow-root
      && wp plugin activate --all --allow-root
      && wp theme activate awk-theme --allow-root
      && wp rewrite structure '/posts/%postname%/' --allow-root
      "