name: Deploy Photo-Stock-WP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .env file
        run: |
          printf "WP_TITLE='Photo stock app'\n" >> .env
          printf "WP_USER=alonecat\n" >> .env
          printf "WP_PASSWORD=1230\n" >> .env
          printf "WP_EMAIL=htchtc052@gmail.com\n" >> .env
          printf "WP_PORT=8080\n" >> .env
          printf "WP_ENV='production'\n" >> .env
          printf "WP_HOME=\"http://localhost:\${WP_PORT}\"\n" >> .env
          printf "WP_SITEURL=\"\${WP_HOME}/wp\"\n" >> .env
          printf "DB_HOST=database:3306\n" >> .env
          printf "DB_NAME='wp'\n" >> .env
          printf "DB_USER='wp'\n" >> .env
          printf "DB_PASSWORD='1230'\n" >> .env
          printf "AUTH_KEY='}UDyqg&*4XwVg|B}Pa;oMp\`sf_xPP]gt&WUM@-cUNW*Jeoys}A}>J[Mx.,K0-yAP'\n" >> .env
          printf "SECURE_AUTH_KEY='*j?=H(2dA(ySJDt1O(K|vp}WNOE;R(,}Ls1ytT#!vaI4);Hr87}_QZx-$6Vu>_r9'\n" >> .env
          printf "LOGGED_IN_KEY='V?2]leu=QQ:)7_j\$S/jQlh0yDQCV)_pH90,G:<ZRsx56ta&,<F\`33#mOB;Qs0Y2s'\n" >> .env
          printf "NONCE_KEY='Te*Z&OyGVP{KzUPY_!A2}(ak9c9J\`7qCplkWHZjDURz:!%%BSj4F^CK(Ea%bFVK<N'\n" >> .env
          printf "AUTH_SALT='D,T-?suf?i}#x8ihMM&#ukGHC9k\$3fw-:AN0Ybo=Hw3@v;[9c8kAOJdSv^-A7xT\`'\n" >> .env
          printf "SECURE_AUTH_SALT='TN\`O3]`N48/pi:[]1vQT;C/CFr9gE0G|:e(Y9m\`aV}1=}b\`C{]cg&;{yU4(O@y2D'\n" >> .env
          printf "LOGGED_IN_SALT='>\$*0\`axaiaRXZU+&%(dp]+yNB8\$9T:5OANWDCVvFX]0G_3qTe\`D:yK&N+-xn56i#'\n" >> .env
          printf "NONCE_SALT=',b4u6jiCb|y,FzX,_\)8zf6Oj7@Lm@;!moM*(m{,a9LwgEVaoh.t{B\`N0&)aLA?9Q'\n" >> .env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Stop and remove old containers, volumes, and images
        run: |
          docker-compose
