name: 'Deploy Photo-Stock-WP'

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      
      x- name: Create .env file
        env:
          WP_TITLE: ${{ secrets.WP_TITLE }}
          WP_USER: ${{ secrets.WP_USER }}
          WP_PASSWORD: ${{ secrets.WP_PASSWORD }}
          WP_EMAIL: ${{ secrets.WP_EMAIL }}
          WP_PORT: ${{ secrets.WP_PORT }}
          WP_ENV: ${{ secrets.WP_ENV }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_PREFIX: ${{ secrets.DB_PREFIX }}
        run: |
          touch .env
          echo "WP_TITLE=\"$WP_TITLE\"" >> .env
          echo "WP_USER=\"$WP_USER\"" >> .env
          echo "WP_PASSWORD=\"$WP_PASSWORD\"" >> .env
          echo "WP_EMAIL=\"$WP_EMAIL\"" >> .env
          echo "WP_PORT=\"$WP_PORT\"" >> .env
          echo "WP_ENV=\"$WP_ENV\"" >> .env
          echo "WP_HOME=\"http://localhost:\${WP_PORT}\"" >> .env
          echo "WP_SITEURL=\"\${WP_HOME}/wp\"" >> .env
          echo "DB_HOST=\"$DB_HOST\"" >> .env
          echo "DB_NAME=\"$DB_NAME\"" >> .env
          echo "DB_USER=\"$DB_USER\"" >> .env
          echo "DB_PASSWORD=\"$DB_PASSWORD\"" >> .env
          echo "DB_PREFIX=\"$DB_PREFIX\"" >> .env

      - name: Build and run Docker containers
        run: |
          docker-compose down --volumes --remove-orphans --rmi all
          docker-compose up -d
